{% set versions = {
    "1.2.0" : "6e00eb56a4f922d03dfceba7b389a3aaf51f277afa46d7b634d661e0797e8898"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "hoppet")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace('/', '.')|replace('-', '.') }}

source:
  url: "https://github.com/hoppet-code/hoppet/archive/refs/tags/hoppet-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('gfortran') }}   # GNU Fortran compiler
    - {{ compiler('c') }}          # GNU C compiler
    - {{ compiler('cxx') }}        # GNU C++ compiler
    
    - cmake                        # Build system
    - make                         # Make utility

about:
  home: "https://github.com/hoppet-code/hoppet"
  license: "GPL-3.0"
  summary: "HOPPET: Higher Order Perturbative Parton Evolution Toolkit"
  description: |
        HOPPET is a Fortran 95 package for carrying out DGLAP evolution and other common manipulations of parton distribution functions (PDFs).

extra:
  recipe-maintainers:
    - meiyasan
