{% set version = environ.get('COMMIT_VERSION', "HEAD") %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "hoppet")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://gitlab.cern.ch/fitters/xfitter"
  git_rev: {{ version }}

requirements:
  build:
    - {{ compiler('gfortran') }}   # GNU Fortran compiler

    - cmake                        # Build system
    - make                         # Make utility
    - python

  host:
    - lhapdf

  run:
    - lhapdf

about:
  home: "https://github.com/hoppet-code/hoppet"
  license: "GPL-3.0"
  summary: "HOPPET: Higher Order Perturbative Parton Evolution Toolkit"
  description: |
        HOPPET is a Fortran 95 package for carrying out DGLAP evolution and other common manipulations of parton distribution functions (PDFs).

extra:
  recipe-maintainers:
    - meiyasan
