{% set versions = {
    "1.3.0": "HEAD",
    "1.2.0": "legacy"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "hoppet")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("hoppet-", "")|replace("-", ".") }}

source:
  git_url: "https://github.com/hoppet-code/hoppet"
  git_rev: {{ versions.get(version, "HEAD") }}

requirements:
  build:
    - {{ compiler('gfortran') }}   # GNU Fortran compiler
    - {{ compiler('c') }}          # GNU C compiler
    - {{ compiler('cxx') }}        # GNU C++ compiler

    - cmake                        # Build system
    - make                         # Make utility
    - python

  host:
    - lhapdf

  run:
    - lhapdf

about:
  home: "https://github.com/hoppet-code/hoppet"
  license: "GPL-3.0"
  summary: "HOPPET: Higher Order Perturbative Parton Evolution Toolkit"
  description: |
        HOPPET is a Fortran 95 package for carrying out DGLAP evolution and other common manipulations of parton distribution functions (PDFs).

extra:
  recipe-maintainers:
    - meiyasan
